services:
  backend: 
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./back-end/.env

  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
