
services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile

    # dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./back-end/.env

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3001:3001


    